/* global systemDictionary:true */
"use strict";

systemDictionary = {
    "group_model": {
        "en": "model",
        "de": "Modell",
        "ru": "модель",
        "pt": "modelo",
        "nl": "model",
        "fr": "modèle",
        "it": "modello",
        "es": "modelo",
        "pl": "Model",
        "zh-cn": "模型"
    },
    "gltf_file": {
        "en": "gltf file",
        "de": "gltf Datei",
        "ru": "gltf файл",
        "pt": "arquivo gltf",
        "nl": "gltf-bestand",
        "fr": "fichier gltf",
        "it": "gltf file",
        "es": "archivo gltf",
        "pl": "plik gltf",
        "zh-cn": "gltf文件"
    },
    "show_loader": {
        "en": "show loading screen",
        "de": "Ladebildschirm anzeigen",
        "ru": "показать экран загрузки",
        "pt": "mostrar tela de carregamento",
        "nl": "toon laadscherm",
        "fr": "afficher l'écran de chargement",
        "it": "mostra la schermata di caricamento",
        "es": "mostrar la pantalla de carga",
        "pl": "pokaż ekran ładowania",
        "zh-cn": "显示载入画面"
    },
    "no 3d model specified": {
        "en": "No 3d model specified",
        "de": "Kein 3D-Modell angegeben",
        "ru": "не указана 3d модель",
        "pt": "nenhum modelo 3D especificado",
        "nl": "geen 3D-model gespecificeerd",
        "fr": "aucun modèle 3D spécifié",
        "it": "nessun modello 3d specificato",
        "es": "sin modelo 3d especificado",
        "pl": "nie określono modelu 3D",
        "zh-cn": "未指定3D模型"
    },
    "group_modellighting": {
        "en": "model lighting",
        "de": "Modellbeleuchtung",
        "ru": "модель освещения",
        "pt": "iluminação modelo",
        "nl": "model verlichting",
        "fr": "éclairage modèle",
        "it": "illuminazione del modello",
        "es": "iluminación modelo",
        "pl": "oświetlenie modelu",
        "zh-cn": "模型照明"
    },
    "model_scene": {
        "en": "scene",
        "de": "Szene",
        "ru": "место действия",
        "pt": "cena",
        "nl": "tafereel",
        "fr": "scène",
        "it": "scena",
        "es": "escena",
        "pl": "scena",
        "zh-cn": "现场"
    },
    "model_pos_x": {
        "en": "model position (<span class=\"axis_x\">x</span>)",
        "de": "Modellposition (<span class=\"axis_x\">x</span>)",
        "ru": "положение модели (<span class=\"axis_x\">x</span>)",
        "pt": "posição do modelo (<span class=\"axis_x\">x</span>)",
        "nl": "model positie (<span class=\"axis_x\">x</span>)",
        "fr": "position du modèle (<span class=\"axis_x\">x</span>)",
        "it": "posizione del modello (<span class=\"axis_x\">x</span>)",
        "es": "posición del modelo (<span class=\"axis_x\">x</span>)",
        "pl": "pozycja modelu (<span class=\"axis_x\">x</span>)",
        "zh-cn": "模特位置(<span class=\"axis_x\">x</span>)"
    },
    "model_pos_y": {
        "en": "model position (<span class=\"axis_y\">y</span>)",
        "de": "Modellposition (<span class=\"axis_y\">y</span>)",
        "ru": "положение модели (<span class=\"axis_y\">y</span>)",
        "pt": "posição do modelo (<span class=\"axis_y\">y</span>)",
        "nl": "model positie (<span class=\"axis_y\">y</span>)",
        "fr": "position du modèle (<span class=\"axis_y\">y</span>)",
        "it": "posizione del modello (<span class=\"axis_y\">y</span>)",
        "es": "posición del modelo (<span class=\"axis_y\">y</span>)",
        "pl": "pozycja modelu (<span class=\"axis_y\">y</span>)",
        "zh-cn": "模特位置(<span class=\"axis_y\">y</span>)"
    },
    "model_pos_z": {
        "en": "model position (<span class=\"axis_z\">z</span>)",
        "de": "Modellposition (<span class=\"axis_z\">z</span>)",
        "ru": "положение модели (<span class=\"axis_z\">z</span>)",
        "pt": "posição do modelo (<span class=\"axis_z\">z</span>)",
        "nl": "model positie (<span class=\"axis_z\">z</span>)",
        "fr": "position du modèle (<span class=\"axis_z\">z</span>)",
        "it": "posizione del modello (<span class=\"axis_z\">z</span>)",
        "es": "posición del modelo (<span class=\"axis_z\">z</span>)",
        "pl": "pozycja modelu (<span class=\"axis_z\">z</span>)",
        "zh-cn": "模特位置(<span class=\"axis_z\">z</span>)"
    },
    "scaling": {
        "en": "scaling",
        "de": "Skalierung",
        "ru": "масштабирование",
        "pt": "escala",
        "nl": "schaalvergroting",
        "fr": "mise à l'échelle",
        "it": "ridimensionamento",
        "es": "escalada",
        "pl": "skalowanie",
        "zh-cn": "缩放"
    },
    "background_color": {
        "en": "background color",
        "de": "Hintergrundfarbe",
        "ru": "фоновый цвет",
        "pt": "cor de fundo",
        "nl": "Achtergrond kleur",
        "fr": "Couleur de l'arrière plan",
        "it": "colore di sfondo",
        "es": "color de fondo",
        "pl": "kolor tła",
        "zh-cn": "背景颜色"
    },
    "group_modelcamera": {
        "en": "camera",
        "de": "Kamera",
        "ru": "камера",
        "pt": "Câmera",
        "nl": "camera",
        "fr": "caméra",
        "it": "telecamera",
        "es": "cámara",
        "pl": "aparat fotograficzny",
        "zh-cn": "相机"
    },
    "model_camera_target_pos_x": {
        "en": "camera target position (<span class=\"axis_x\">x</span>)",
        "de": "Zielposition der Kamera (<span class=\"axis_x\">x</span>)",
        "ru": "целевое положение камеры (<span class=\"axis_x\">x</span>)",
        "pt": "posição do alvo da câmera (<span class=\"axis_x\">x</span>)",
        "nl": "camera doelpositie (<span class=\"axis_x\">x</span>)",
        "fr": "position cible de la caméra (<span class=\"axis_x\">x</span>)",
        "it": "posizione di destinazione della telecamera (<span class=\"axis_x\">x</span>)",
        "es": "posición del objetivo de la cámara (<span class=\"axis_x\">x</span>)",
        "pl": "położenie celu kamery (<span class=\"axis_x\">x</span>)",
        "zh-cn": "相机目标位置 (<span class=\"axis_x\">x</span>)"
    },
    "model_camera_target_pos_y": {
        "en": "camera target position (<span class=\"axis_y\">y</span>)",
        "de": "Zielposition der Kamera (<span class=\"axis_y\">y</span>)",
        "ru": "целевое положение камеры (<span class=\"axis_y\">y</span>)",
        "pt": "posição do alvo da câmera (<span class=\"axis_y\">y</span>)",
        "nl": "camera doelpositie (<span class=\"axis_y\">y</span>)",
        "fr": "position cible de la caméra (<span class=\"axis_y\">y</span>)",
        "it": "posizione di destinazione della telecamera (<span class=\"axis_y\">y</span>)",
        "es": "posición del objetivo de la cámara (<span class=\"axis_y\">y</span>)",
        "pl": "położenie celu kamery (<span class=\"axis_y\">y</span>)",
        "zh-cn": "相机目标位置 (<span class=\"axis_y\">y</span>)"
    },
    "model_camera_target_pos_z": {
        "en": "camera target position (<span class=\"axis_z\">z</span>)",
        "de": "Zielposition der Kamera (<span class=\"axis_z\">z</span>)",
        "ru": "целевое положение камеры (<span class=\"axis_z\">z</span>)",
        "pt": "posição do alvo da câmera (<span class=\"axis_z\">z</span>)",
        "nl": "camera doelpositie (<span class=\"axis_z\">z</span>)",
        "fr": "position cible de la caméra (<span class=\"axis_z\">z</span>)",
        "it": "posizione di destinazione della telecamera (<span class=\"axis_z\">z</span>)",
        "es": "posición del objetivo de la cámara (<span class=\"axis_z\">z</span>)",
        "pl": "położenie celu kamery (<span class=\"axis_z\">z</span>)",
        "zh-cn": "相机目标位置 (<span class=\"axis_z\">z</span>)"
    },
    "model_camera_pos_x": {
        "en": "camera position (<span class=\"axis_x\">x</span>)",
        "de": "Kameraposition (<span class=\"axis_x\">x</span>)",
        "ru": "положение камеры (<span class=\"axis_x\">x</span>)",
        "pt": "posição da câmera (<span class=\"axis_x\">x</span>)",
        "nl": "camerapositie (<span class=\"axis_x\">x</span>)",
        "fr": "position de la caméra (<span class=\"axis_x\">x</span>)",
        "it": "posizione della telecamera (<span class=\"axis_x\">x</span>)",
        "es": "posición de la cámara (<span class=\"axis_x\">x</span>)",
        "pl": "położenie kamery (<span class=\"axis_x\">x</span>)",
        "zh-cn": "相机位置 (<span class=\"axis_x\">x</span>)"
    },
    "model_camera_pos_y": {
        "en": "camera position (<span class=\"axis_y\">y</span>)",
        "de": "Kameraposition (<span class=\"axis_y\">y</span>)",
        "ru": "положение камеры (<span class=\"axis_y\">y</span>)",
        "pt": "posição da câmera (<span class=\"axis_y\">y</span>)",
        "nl": "camerapositie (<span class=\"axis_y\">y</span>)",
        "fr": "position de la caméra (<span class=\"axis_y\">y</span>)",
        "it": "posizione della telecamera (<span class=\"axis_y\">y</span>)",
        "es": "posición de la cámara (<span class=\"axis_y\">y</span>)",
        "pl": "położenie kamery (<span class=\"axis_y\">y</span>)",
        "zh-cn": "相机位置 (<span class=\"axis_y\">y</span>)"
    },
    "model_camera_pos_z": {
        "en": "camera position (<span class=\"axis_z\">z</span>)",
        "de": "Kameraposition (<span class=\"axis_z\">z</span>)",
        "ru": "положение камеры (<span class=\"axis_z\">z</span>)",
        "pt": "posição da câmera (<span class=\"axis_z\">z</span>)",
        "nl": "camerapositie (<span class=\"axis_z\">z</span>)",
        "fr": "position de la caméra (<span class=\"axis_z\">z</span>)",
        "it": "posizione della telecamera (<span class=\"axis_z\">z</span>)",
        "es": "posición de la cámara (<span class=\"axis_z\">z</span>)",
        "pl": "położenie kamery (<span class=\"axis_z\">z</span>)",
        "zh-cn": "相机位置 (<span class=\"axis_z\">z</span>)"
    },
    "enable_realistic_lighting": {
        "en": "realistic lighting",
        "de": "realistische Beleuchtung",
        "ru": "реалистичное освещение",
        "pt": "iluminação realista",
        "nl": "realistische verlichting",
        "fr": "éclairage réaliste",
        "it": "illuminazione realistica",
        "es": "iluminación realista",
        "pl": "realistyczne oświetlenie",
        "zh-cn": "逼真的照明"
    },
    "enable_ambient_lighting": {
        "en": "ambient lighting",
        "de": "Umgebungsbeleuchtung",
        "ru": "окружающее освещение",
        "pt": "iluminação ambiente",
        "nl": "sfeerverlichting",
        "fr": "éclairage ambiant",
        "it": "illuminazione dell'ambiente",
        "es": "iluminación ambiental",
        "pl": "otaczające światło",
        "zh-cn": "环境照明"
    },
    "ambient_color": {
        "en": "ambient color",
        "de": "Umgebungsfarbe",
        "ru": "окружающий цвет",
        "pt": "cor ambiente",
        "nl": "omgevingskleur",
        "fr": "couleur ambiante",
        "it": "colore ambientale",
        "es": "color ambiental",
        "pl": "kolor otoczenia",
        "zh-cn": "环境颜色"
    },
    "ambient_intensity": {
        "en": "ambient intensity",
        "de": "Umgebungsintensität",
        "ru": "интенсивность окружающей среды",
        "pt": "intensidade ambiente",
        "nl": "omgevingsintensiteit",
        "fr": "intensité ambiante",
        "it": "intensità ambientale",
        "es": "intensidad ambiental",
        "pl": "intensywność otoczenia",
        "zh-cn": "环境强度"
    },
    "enable_hemispheric_lighting": {
        "en": "hemispheric lighting",
        "de": "halbkugelförmige Beleuchtung",
        "ru": "полусферическое освещение",
        "pt": "iluminação hemisférica",
        "nl": "hemisferische verlichting",
        "fr": "éclairage hémisphérique",
        "it": "illuminazione emisferica",
        "es": "iluminación hemisférica",
        "pl": "oświetlenie półkuliste",
        "zh-cn": "半球照明"
    },
    "punctual_lights_max_power": {
        "en": "punct-lights max power",
        "de": "Punktlichter maximale Leistung",
        "ru": "максимальная мощность светильников",
        "pt": "potência máxima das luzes punct",
        "nl": "punct-lights max. vermogen",
        "fr": "puissance maximale de punct-lights",
        "it": "potenza massima luci puntiforme",
        "es": "punct-lights potencia máxima",
        "pl": "maksymalna moc świateł punktowych",
        "zh-cn": "点光源最大功率"
    },
    "light_max_power": {
        "en": "light max power",
        "de": "Licht max Leistung",
        "ru": "максимальная мощность света",
        "pt": "potência máxima de luz",
        "nl": "licht max. vermogen",
        "fr": "puissance maximale légère",
        "it": "potenza massima leggera",
        "es": "potencia máxima ligera",
        "pl": "światło maksymalna moc",
        "zh-cn": "最大光功率"
    },
    "light_monitored_state_max_value": {
        "en": "state max value",
        "de": "Zustand max Wert",
        "ru": "указать максимальное значение",
        "pt": "valor máximo do estado",
        "nl": "max. waarde aangeven",
        "fr": "état valeur max",
        "it": "indicare il valore massimo",
        "es": "estado valor máximo",
        "pl": "wartość maksymalna stanu",
        "zh-cn": "状态最大值"
    },
    "number_switchable_lights": {
        "en": "number of switchable lights",
        "de": "Anzahl der schaltbaren Lichter",
        "ru": "количество переключаемых огней",
        "pt": "número de luzes comutáveis",
        "nl": "aantal schakelbare lampen",
        "fr": "nombre de lumières commutables",
        "it": "numero di luci commutabili",
        "es": "número de luces conmutables",
        "pl": "liczba włączanych świateł",
        "zh-cn": "可切换灯的数量"
    },
    "group_modelswitchablelights": {
        "en": "switchable lights",
        "de": "Schaltbare Lichter",
        "ru": "переключаемый свет",
        "pt": "luzes comutáveis",
        "nl": "schakelbare verlichting",
        "fr": "lumières commutables",
        "it": "luci commutabili",
        "es": "luces conmutables",
        "pl": "włączane światła",
        "zh-cn": "开关灯"
    },
    "light_name": {
        "en": "light name",
        "de": "Licht Name",
        "ru": "свет имя",
        "pt": "luz nome",
        "nl": "licht naam",
        "fr": "lumière nom",
        "it": "luce nome",
        "es": "ligero nombre",
        "pl": "światło naszwa",
        "zh-cn": "光 名称"
    },
    "light_monitored_state": {
        "en": "monitored state",
        "de": "überwachter Zustand",
        "ru": "контролируемое состояние",
        "pt": "estado monitorado",
        "nl": "bewaakte staat",
        "fr": "état surveillé",
        "it": "stato monitorato",
        "es": "estado monitoreado",
        "pl": "monitorowany stan",
        "zh-cn": "监视状态"
    },
    "group_modelanimations": {
        "en": "animations",
        "de": "Animationen",
        "ru": "анимации",
        "pt": "animações",
        "nl": "animaties",
        "fr": "animations",
        "it": "animazioni",
        "es": "animaciones",
        "pl": "animacje",
        "zh-cn": "动画"
    },
    "highlight_selected": {
        "en": "highlight selection",
        "de": "Auswahl markieren",
        "ru": "выделить выбор",
        "pt": "seleção de destaque",
        "nl": "markeer selectie",
        "fr": "sélection de surbrillance",
        "it": "evidenziare la selezione",
        "es": "resaltar la selección",
        "pl": "zaznacz zaznaczenie",
        "zh-cn": "高亮选择"
    },
    "highlight_color": {
        "en": "highlight color",
        "de": "Hervorhebungsfarbe",
        "ru": "цвет выделения",
        "pt": "cor de destaque",
        "nl": "markeer kleur",
        "fr": "couleur de surbrillance",
        "it": "evidenziare il colore",
        "es": "resaltar el color",
        "pl": "podświetlony kolor",
        "zh-cn": "突出显示颜色"
    },
    "number_clickable_objects": {
        "en": "number of clickable objects",
        "de": "Anzahl anklickbarer Objekte",
        "ru": "количество кликабельных объектов",
        "pt": "número de objetos clicáveis",
        "nl": "aantal klikbare objecten",
        "fr": "nombre d'objets cliquables",
        "it": "numero di oggetti cliccabili",
        "es": "número de objetos en los que se puede hacer clic",
        "pl": "liczba klikalnych obiektów",
        "zh-cn": "可点击对象的数量"
    },
    "number_animations": {
        "en": "number of animations",
        "de": "Anzahl der Animationen",
        "ru": "количество анимаций",
        "pt": "número de animações",
        "nl": "aantal animaties",
        "fr": "nombre d'animations",
        "it": "numero di animazioni",
        "es": "número de animaciones",
        "pl": "liczba animacji",
        "zh-cn": "动画数量"
    },
    "animation_behaviour": {
        "en": "behaviour",
        "de": "Verhalten",
        "ru": "поведение",
        "pt": "comportamento",
        "nl": "gedrag",
        "fr": "comportement",
        "it": "comportamento",
        "es": "comportamiento",
        "pl": "zachowanie",
        "zh-cn": "行为"
    },
    "monitored_state_name": {
        "en": "monitored state",
        "de": "überwachter Zustand",
        "ru": "контролируемое состояние",
        "pt": "estado monitorado",
        "nl": "bewaakte staat",
        "fr": "état surveillé",
        "it": "stato monitorato",
        "es": "estado monitoreado",
        "pl": "monitorowany stan",
        "zh-cn": "监视状态"
    },
    "monitored_state_max_value": {
        "en": "state max value",
        "de": "Zustand max Wert",
        "ru": "указать максимальное значение",
        "pt": "valor máximo do estado",
        "nl": "max. waarde aangeven",
        "fr": "état valeur max",
        "it": "indicare il valore massimo",
        "es": "estado valor máximo",
        "pl": "wartość maksymalna stanu",
        "zh-cn": "状态最大值"
    },
    "monitorstate": {
        "en": "monitor state",
        "de": "Status überwachen",
        "ru": "состояние монитора",
        "pt": "monitorar estado",
        "nl": "monitor staat",
        "fr": "état du moniteur",
        "it": "monitorare lo stato",
        "es": "estado del monitor",
        "pl": "stan monitora",
        "zh-cn": "监控状态"
    },
    "autoplay": {
        "en": "auto play",
        "de": "automatisches Abspielen",
        "ru": "Автовоспроизведение",
        "pt": "Reprodução automática",
        "nl": "automatisch afspelen",
        "fr": "lecture automatique",
        "it": "riproduzione automatica",
        "es": "auto-reproducción",
        "pl": "Automatyczne odtwarzanie",
        "zh-cn": "自动播放"
    },
    "animation": {
        "en": "animation",
        "de": "Animation",
        "ru": "анимация",
        "pt": "animação",
        "nl": "animatie",
        "fr": "animation",
        "it": "animazione",
        "es": "animación",
        "pl": "animacja",
        "zh-cn": "动画"
    },
    "animation_repeat": {
        "en": "repeat",
        "de": "wiederholen",
        "ru": "повторение",
        "pt": "repetir",
        "nl": "herhaling",
        "fr": "répéter",
        "it": "ripetere",
        "es": "repetir",
        "pl": "powtarzać",
        "zh-cn": "重复"
    },
    "group_modelclickableobjects": {
        "en": "clickable objects",
        "de": "Anklickbare Objekte",
        "ru": "интерактивные объекты",
        "pt": "objetos clicáveis",
        "nl": "klikbare objecten",
        "fr": "objets cliquables",
        "it": "oggetti cliccabili",
        "es": "objetos en los que se puede hacer clic",
        "pl": "klikalne obiekty",
        "zh-cn": "可点击的对象"
    },
    "clickable_object_name": {
        "en": "object name",
        "de": "Objektname",
        "ru": "имя объекта",
        "pt": "nome do objeto",
        "nl": "objectnaam",
        "fr": "nom de l'objet",
        "it": "nome oggetto",
        "es": "nombre del objeto",
        "pl": "nazwa obiektu",
        "zh-cn": "对象名称"
    },
    "clickable_object_state": {
        "en": "changeable state",
        "de": "veränderbarer Zustand",
        "ru": "изменчивое состояние",
        "pt": "estado mutável",
        "nl": "veranderlijke staat",
        "fr": "état variable",
        "it": "stato mutevole",
        "es": "estado cambiante",
        "pl": "zmienny stan",
        "zh-cn": "可变状态"
    },
    "clickable_object_state_action": {
        "en": "action",
        "de": "Aktion",
        "ru": "действие",
        "pt": "açao",
        "nl": "actie",
        "fr": "action",
        "it": "azione",
        "es": "acción",
        "pl": "akcja",
        "zh-cn": "行动"
    },
    "enable": {
        "en": "enable",
        "de": "aktivieren",
        "ru": "включить",
        "pt": "habilitar",
        "nl": "inschakelen",
        "fr": "activer",
        "it": "abilitare",
        "es": "habilitar",
        "pl": "włączyć",
        "zh-cn": "使能"
    },
    "disable": {
        "en": "disable",
        "de": "deaktivieren",
        "ru": "отключить",
        "pt": "desabilitar",
        "nl": "uitschakelen",
        "fr": "désactiver",
        "it": "disattivare",
        "es": "inhabilitar",
        "pl": "wyłączyć",
        "zh-cn": "禁用"
    },
    "toggle": {
        "en": "toggle",
        "de": "Umschalten",
        "ru": "переключить",
        "pt": "alternancia",
        "nl": "schakelen",
        "fr": "basculer",
        "it": "toggle",
        "es": "palanca",
        "pl": "przełącznik",
        "zh-cn": "拨动"
    },
    "enable_shadows": {
        "en": "calculate shadows",
        "de": "Schatten berechnen",
        "ru": "вычислить тени",
        "pt": "calcular sombras",
        "nl": "bereken schaduwen",
        "fr": "calculer les ombres",
        "it": "calcolare le ombre",
        "es": "calcular sombras",
        "pl": "oblicz cienie",
        "zh-cn": "计算阴影"
    },
    "silent": {
        "en": "silent",
        "de": "silent",
        "ru": "silent",
        "pt": "silent",
        "nl": "silent",
        "fr": "silent",
        "it": "silent",
        "es": "silent",
        "pl": "silent",
        "zh-cn": "silent"
    },
    "error": {
        "en": "error",
        "de": "error",
        "ru": "error",
        "pt": "error",
        "nl": "error",
        "fr": "error",
        "it": "error",
        "es": "error",
        "pl": "error",
        "zh-cn": "error"
    },
    "warn": {
        "en": "warn",
        "de": "warn",
        "ru": "warn",
        "pt": "warn",
        "nl": "warn",
        "fr": "warn",
        "it": "warn",
        "es": "warn",
        "pl": "warn",
        "zh-cn": "warn"
    },
    "info": {
        "en": "info",
        "de": "info",
        "ru": "info",
        "pt": "info",
        "nl": "info",
        "fr": "info",
        "it": "info",
        "es": "info",
        "pl": "info",
        "zh-cn": "info"
    },
    "debug": {
        "en": "debug",
        "de": "debug",
        "ru": "debug",
        "pt": "debug",
        "nl": "debug",
        "fr": "debug",
        "it": "debug",
        "es": "debug",
        "pl": "debug",
        "zh-cn": "debug"
    },
    "trace": {
        "en": "trace",
        "de": "trace",
        "ru": "trace",
        "pt": "trace",
        "nl": "trace",
        "fr": "trace",
        "it": "trace",
        "es": "trace",
        "pl": "trace",
        "zh-cn": "trace"
    },
    "group_modeldebug": {
        "en": "debugging",
        "de": "Debuggen",
        "ru": "отладка",
        "pt": "depuração",
        "nl": "debuggen",
        "fr": "débogage",
        "it": "debug",
        "es": "depuración",
        "pl": "debugowanie",
        "zh-cn": "调试"
    },
    "debug_loglevel": {
        "en": "loglevel",
        "de": "Loglevel",
        "ru": "лог-уровень",
        "pt": "loglevel",
        "nl": "Log niveau",
        "fr": "loglevel",
        "it": "loglevel",
        "es": "nivel de registro",
        "pl": "loglevel",
        "zh-cn": "日志级别"
    }
};
