/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "group_model": {
        "en": "model",
        "de": "Modell",
        "ru": "модель",
        "pt": "modelo",
        "nl": "model",
        "fr": "modèle",
        "it": "modello",
        "es": "modelo",
        "pl": "Model",
        "zh-cn": "模型"
    },
    "gltf_file": {
      "en": "gltf file",
      "de": "gltf Datei",
      "ru": "gltf файл",
      "pt": "arquivo gltf",
      "nl": "gltf-bestand",
      "fr": "fichier gltf",
      "it": "gltf file",
      "es": "archivo gltf",
      "pl": "plik gltf",
      "zh-cn": "gltf文件"
    },
    "group_modellighting": {
        "en": "model lighting",
        "de": "Modellbeleuchtung",
        "ru": "модель освещения",
        "pt": "iluminação modelo",
        "nl": "model verlichting",
        "fr": "éclairage modèle",
        "it": "illuminazione del modello",
        "es": "iluminación modelo",
        "pl": "oświetlenie modelu",
        "zh-cn": "模型照明"
    },
    "model_scene": {
        "en": "scene",
        "de": "Szene",
        "ru": "место действия",
        "pt": "cena",
        "nl": "tafereel",
        "fr": "scène",
        "it": "scena",
        "es": "escena",
        "pl": "scena",
        "zh-cn": "现场"
    },
    "model_pos_x": {
        "en": "model position x",
        "de": "Modellposition x",
        "ru": "положение модели x",
        "pt": "posição do modelo x",
        "nl": "model positie x",
        "fr": "position du modèle x",
        "it": "posizione del modello x",
        "es": "posición del modelo x",
        "pl": "pozycja modelu x",
        "zh-cn": "模特位置x"
    },
    "model_pos_y": {
        "en": "model position y",
        "de": "Modellposition y",
        "ru": "положение модели y",
        "pt": "posição do modelo y",
        "nl": "model positie y",
        "fr": "position du modèle y",
        "it": "posizione del modello y",
        "es": "posición del modelo y",
        "pl": "pozycja modelu y",
        "zh-cn": "模特位置y"
    },
    "model_pos_z": {
        "en": "model position z",
        "de": "Modellposition z",
        "ru": "положение модели z",
        "pt": "posição do modelo z",
        "nl": "model positie z",
        "fr": "position du modèle z",
        "it": "posizione del modello z",
        "es": "posición del modelo z",
        "pl": "pozycja modelu z",
        "zh-cn": "模特位置z"
    },
    "scaling": {
        "en": "scaling",
        "de": "Skalierung",
        "ru": "масштабирование",
        "pt": "escala",
        "nl": "schaalvergroting",
        "fr": "mise à l'échelle",
        "it": "ridimensionamento",
        "es": "escalada",
        "pl": "skalowanie",
        "zh-cn": "缩放"
      },
      "background_color": {
        "en": "background color",
        "de": "Hintergrundfarbe",
        "ru": "фоновый цвет",
        "pt": "cor de fundo",
        "nl": "Achtergrond kleur",
        "fr": "Couleur de l'arrière plan",
        "it": "colore di sfondo",
        "es": "color de fondo",
        "pl": "kolor tła",
        "zh-cn": "背景颜色"
      },
      "group_modelcamera": {
        "en": "camera",
        "de": "Kamera",
        "ru": "камера",
        "pt": "Câmera",
        "nl": "camera",
        "fr": "caméra",
        "it": "telecamera",
        "es": "cámara",
        "pl": "aparat fotograficzny",
        "zh-cn": "相机"
      },
      "model_camera_target_pos_x": {
        "en": "camera target position (x)",
        "de": "Zielposition der Kamera (x)",
        "ru": "целевое положение камеры (x)",
        "pt": "posição do alvo da câmera (x)",
        "nl": "camera doelpositie (x)",
        "fr": "position cible de la caméra (x)",
        "it": "posizione di destinazione della telecamera (x)",
        "es": "posición del objetivo de la cámara (x)",
        "pl": "położenie celu kamery (x)",
        "zh-cn": "相机目标位置 (x)"
      },
      "model_camera_target_pos_y": {
        "en": "camera target position (y)",
        "de": "Zielposition der Kamera (y)",
        "ru": "целевое положение камеры (y)",
        "pt": "posição do alvo da câmera (y)",
        "nl": "camera doelpositie (y)",
        "fr": "position cible de la caméra (y)",
        "it": "posizione di destinazione della telecamera (y)",
        "es": "posición del objetivo de la cámara (y)",
        "pl": "położenie celu kamery (y)",
        "zh-cn": "相机目标位置 (y)"
      },
      "model_camera_target_pos_z": {
        "en": "camera target position (z)",
        "de": "Zielposition der Kamera (z)",
        "ru": "целевое положение камеры (z)",
        "pt": "posição do alvo da câmera (z)",
        "nl": "camera doelpositie (z)",
        "fr": "position cible de la caméra (z)",
        "it": "posizione di destinazione della telecamera (z)",
        "es": "posición del objetivo de la cámara (z)",
        "pl": "położenie celu kamery (z)",
        "zh-cn": "相机目标位置 (z)"
      },
      "model_camera_ pos_x": {
        "en": "camera position (x)",
        "de": "Kameraposition (x)",
        "ru": "положение камеры (x)",
        "pt": "posição da câmera (x)",
        "nl": "camerapositie (x)",
        "fr": "position de la caméra (x)",
        "it": "posizione della telecamera (x)",
        "es": "posición de la cámara (x)",
        "pl": "położenie kamery (x)",
        "zh-cn": "相机位置 (x)"
      },
      "model_camera_ pos_y": {
        "en": "camera position (y)",
        "de": "Kameraposition (y)",
        "ru": "положение камеры (y)",
        "pt": "posição da câmera (y)",
        "nl": "camerapositie (y)",
        "fr": "position de la caméra (y)",
        "it": "posizione della telecamera (y)",
        "es": "posición de la cámara (y)",
        "pl": "położenie kamery (y)",
        "zh-cn": "相机位置 (y)"
      },
      "model_camera_ pos_x": {
        "en": "camera position (x)",
        "de": "Kameraposition (x)",
        "ru": "положение камеры (x)",
        "pt": "posição da câmera (x)",
        "nl": "camerapositie (x)",
        "fr": "position de la caméra (x)",
        "it": "posizione della telecamera (x)",
        "es": "posición de la cámara (x)",
        "pl": "położenie kamery (x)",
        "zh-cn": "相机位置 (x)"
      },
      "enable_realistic_lighting": {
        "en": "realistic lighting",
        "de": "realistische Beleuchtung",
        "ru": "реалистичное освещение",
        "pt": "iluminação realista",
        "nl": "realistische verlichting",
        "fr": "éclairage réaliste",
        "it": "illuminazione realistica",
        "es": "iluminación realista",
        "pl": "realistyczne oświetlenie",
        "zh-cn": "逼真的照明"
      },
      "enable_ambient_lighting": {
        "en": "ambient lighting",
        "de": "Umgebungsbeleuchtung",
        "ru": "окружающее освещение",
        "pt": "iluminação ambiente",
        "nl": "sfeerverlichting",
        "fr": "éclairage ambiant",
        "it": "illuminazione dell'ambiente",
        "es": "iluminación ambiental",
        "pl": "otaczające światło",
        "zh-cn": "环境照明"
      },
      "ambient_color": {
        "en": "ambient color",
        "de": "Umgebungsfarbe",
        "ru": "окружающий цвет",
        "pt": "cor ambiente",
        "nl": "omgevingskleur",
        "fr": "couleur ambiante",
        "it": "colore ambientale",
        "es": "color ambiental",
        "pl": "kolor otoczenia",
        "zh-cn": "环境颜色"
      },
      "ambient_intensity": {
        "en": "ambient intensity",
        "de": "Umgebungsintensität",
        "ru": "интенсивность окружающей среды",
        "pt": "intensidade ambiente",
        "nl": "omgevingsintensiteit",
        "fr": "intensité ambiante",
        "it": "intensità ambientale",
        "es": "intensidad ambiental",
        "pl": "intensywność otoczenia",
        "zh-cn": "环境强度"
      },
      "enable_hemispheric_lighting": {
        "en": "hemispheric lighting",
        "de": "halbkugelförmige Beleuchtung",
        "ru": "полусферическое освещение",
        "pt": "iluminação hemisférica",
        "nl": "hemisferische verlichting",
        "fr": "éclairage hémisphérique",
        "it": "illuminazione emisferica",
        "es": "iluminación hemisférica",
        "pl": "oświetlenie półkuliste",
        "zh-cn": "半球照明"
      },
      "number_switchable_lights": {
        "en": "number of switchable lights",
        "de": "Anzahl der schaltbaren Lichter",
        "ru": "количество переключаемых огней",
        "pt": "número de luzes comutáveis",
        "nl": "aantal schakelbare lampen",
        "fr": "nombre de lumières commutables",
        "it": "numero di luci commutabili",
        "es": "número de luces conmutables",
        "pl": "liczba włączanych świateł",
        "zh-cn": "可切换灯的数量"
      },
      "group_modelswitchablelights": {
        "en": "switchable lights",
        "de": "Schaltbare Lichter",
        "ru": "переключаемый свет",
        "pt": "luzes comutáveis",
        "nl": "schakelbare verlichting",
        "fr": "lumières commutables",
        "it": "luci commutabili",
        "es": "luces conmutables",
        "pl": "włączane światła",
        "zh-cn": "开关灯"
      },
      "light_name": {
        "en": "light name",
        "de": "Licht Name",
        "ru": "свет имя",
        "pt": "luz nome",
        "nl": "licht naam",
        "fr": "lumière nom",
        "it": "luce nome",
        "es": "ligero nombre",
        "pl": "światło naszwa",
        "zh-cn": "光 名称"
      },
      "light_monitored_state": {
        "en": "monitored state",
        "de": "überwachter Zustand",
        "ru": "контролируемое состояние",
        "pt": "estado monitorado",
        "nl": "bewaakte staat",
        "fr": "état surveillé",
        "it": "stato monitorato",
        "es": "estado monitoreado",
        "pl": "monitorowany stan",
        "zh-cn": "监视状态"
      },
      "group_modelanimations": {
        "en": "animations",
        "de": "Animationen",
        "ru": "анимации",
        "pt": "animações",
        "nl": "animaties",
        "fr": "animations",
        "it": "animazioni",
        "es": "animaciones",
        "pl": "animacje",
        "zh-cn": "动画"
      },
      "highlight_selected": {
        "en": "highlight selection",
        "de": "Auswahl markieren",
        "ru": "выделить выбор",
        "pt": "seleção de destaque",
        "nl": "markeer selectie",
        "fr": "sélection de surbrillance",
        "it": "evidenziare la selezione",
        "es": "resaltar la selección",
        "pl": "zaznacz zaznaczenie",
        "zh-cn": "高亮选择"
      },
      "highlight_color": {
        "en": "highlight color",
        "de": "Hervorhebungsfarbe",
        "ru": "цвет выделения",
        "pt": "cor de destaque",
        "nl": "markeer kleur",
        "fr": "couleur de surbrillance",
        "it": "evidenziare il colore",
        "es": "resaltar el color",
        "pl": "podświetlony kolor",
        "zh-cn": "突出显示颜色"
      },
      "number_clickable_objects": {
        "en": "number of clickable objects",
        "de": "Anzahl anklickbarer Objekte",
        "ru": "количество кликабельных объектов",
        "pt": "número de objetos clicáveis",
        "nl": "aantal klikbare objecten",
        "fr": "nombre d'objets cliquables",
        "it": "numero di oggetti cliccabili",
        "es": "número de objetos en los que se puede hacer clic",
        "pl": "liczba klikalnych obiektów",
        "zh-cn": "可点击对象的数量"
      },
      "number_animations": {
        "en": "number of animations",
        "de": "Anzahl der Animationen",
        "ru": "количество анимаций",
        "pt": "número de animações",
        "nl": "aantal animaties",
        "fr": "nombre d'animations",
        "it": "numero di animazioni",
        "es": "número de animaciones",
        "pl": "liczba animacji",
        "zh-cn": "动画数量"
      },
      "group_modelclickableobjects": {
        "en": "clickable objects",
        "de": "Anklickbare Objekte",
        "ru": "интерактивные объекты",
        "pt": "objetos clicáveis",
        "nl": "klikbare objecten",
        "fr": "objets cliquables",
        "it": "oggetti cliccabili",
        "es": "objetos en los que se puede hacer clic",
        "pl": "klikalne obiekty",
        "zh-cn": "可点击的对象"
      },
      "clickable_object_name": {
        "en": "object name",
        "de": "Objektname",
        "ru": "имя объекта",
        "pt": "nome do objeto",
        "nl": "objectnaam",
        "fr": "nom de l'objet",
        "it": "nome oggetto",
        "es": "nombre del objeto",
        "pl": "nazwa obiektu",
        "zh-cn": "对象名称"
      },
      "enable_shadows": {
        "en": "calculate shadows",
        "de": "Schatten berechnen",
        "ru": "вычислить тени",
        "pt": "calcular sombras",
        "nl": "bereken schaduwen",
        "fr": "calculer les ombres",
        "it": "calcolare le ombre",
        "es": "calcular sombras",
        "pl": "oblicz cienie",
        "zh-cn": "计算阴影"
      }
};